import { Alert, Linking, Platform, Share } from "react-native";
import type { PatientData } from "@/context/PatientContext";

export const EMERGENCY_NUMBER = "112";

/**
 * Prompt the user to confirm, then dial the national emergency number.
 * Ireland / EU: 112 (also 999). No-op with an alert on web.
 */
export function callEmergencyServices() {
  if (Platform.OS === "web") {
    Alert.alert(
      "Emergency Services",
      `On a phone this dials ${EMERGENCY_NUMBER}. If this is an emergency, call ${EMERGENCY_NUMBER} (or 999) now.`
    );
    return;
  }
  Alert.alert(
    "Call Emergency Services?",
    `This will dial ${EMERGENCY_NUMBER} (999). Only call in a genuine medical emergency.`,
    [
      { text: "Cancel", style: "cancel" },
      {
        text: `Call ${EMERGENCY_NUMBER}`,
        style: "destructive",
        onPress: () => {
          Linking.openURL(`tel:${EMERGENCY_NUMBER}`).catch(() => {
            Alert.alert("Unable to place call", `Please dial ${EMERGENCY_NUMBER} manually.`);
          });
        },
      },
    ]
  );
}

/** Build a human-readable summary of the patient's health card for handover. */
export function formatPatientCard(data: PatientData): string {
  const conditions = data.medicalHistory.length
    ? data.medicalHistory
        .map((c) => `  • ${c.name}${c.icd10 ? ` (${c.icd10})` : ""} — ${c.status}`)
        .join("\n")
    : "  • None recorded";

  const allergies = data.allergies.length
    ? data.allergies
        .map((a) => `  • ${a.drug} — ${a.reaction} [${a.severity}]`)
        .join("\n")
    : "  • None recorded";

  const meds = data.kardex.filter((k) => k.status === "active");
  const medsText = meds.length
    ? meds.map((m) => `  • ${m.medication} ${m.dose} — ${m.frequency} (${m.route})`).join("\n")
    : "  • None recorded";

  return [
    "PATIENT HEALTH CARD",
    "",
    "Medical conditions:",
    conditions,
    "",
    "Drug allergies:",
    allergies,
    "",
    "Current medications:",
    medsText,
  ].join("\n");
}

const DISCLAIMER =
  "This summary was generated by HIVE Bot (IbnCeena Health Ecosystem) for clinical handover. It is guidance only and not a substitute for professional medical assessment.";

/**
 * Share a text summary with health services / a clinician via the native
 * share sheet. Falls back to the Web Share API or an alert on web.
 */
export async function shareWithHealthServices(title: string, body: string) {
  const message = `${title}\nGenerated: ${new Date().toLocaleString()}\n\n${body}\n\n${DISCLAIMER}`;

  if (Platform.OS === "web") {
    const nav = typeof navigator !== "undefined" ? (navigator as Navigator & { share?: (d: ShareData) => Promise<void> }) : undefined;
    if (nav?.share) {
      try {
        await nav.share({ title, text: message });
        return;
      } catch {
        /* user cancelled or unsupported — fall through */
      }
    }
    Alert.alert(title, message);
    return;
  }

  try {
    await Share.share({ title, message });
  } catch {
    Alert.alert("Unable to share", "Please try again.");
  }
}
