// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/HealthCardSaveToPhotos.tsx": () => import("../components/mockups/HealthCardSaveToPhotos.tsx"),
  "./components/mockups/login-variations/BiometricQuick.tsx": () => import("../components/mockups/login-variations/BiometricQuick.tsx"),
  "./components/mockups/login-variations/EmergencyEntry.tsx": () => import("../components/mockups/login-variations/EmergencyEntry.tsx"),
  "./components/mockups/login-variations/PathGateway.tsx": () => import("../components/mockups/login-variations/PathGateway.tsx"),
  "./components/mockups/login-variations/TrustFirstPortal.tsx": () => import("../components/mockups/login-variations/TrustFirstPortal.tsx")
};
