#!/usr/bin/env node
// scripts/extract-envs.js
// Scans the repository for environment variable usages (process.env and import.meta.env)
// and writes a .env.example to stdout or to a file when --write is passed.
// Usage:
//   node scripts/extract-envs.js [path]            # prints .env.example to stdout
//   node scripts/extract-envs.js [path] --write    # writes .env.example to repo root

const fs = require('fs');
const path = require('path');

const rootArg = process.argv[2];
const writeFlag = process.argv.includes('--write');
const root = rootArg && !rootArg.startsWith('--') ? path.resolve(rootArg) : process.cwd();

const exts = new Set(['.js', '.ts', '.tsx', '.jsx', '.mjs', '.cjs']);
const envKeys = new Set();

function walk(dir) {
  let items;
  try {
    items = fs.readdirSync(dir, { withFileTypes: true });
  } catch (e) {
    return;
  }

  for (const it of items) {
    if (it.name === 'node_modules' || it.name.startsWith('.git') || it.name === '.next' || it.name === 'dist') continue;
    const full = path.join(dir, it.name);
    if (it.isDirectory()) walk(full);
    else {
      if (!exts.has(path.extname(it.name))) continue;
      let content;
      try {
        content = fs.readFileSync(full, 'utf8');
      } catch (e) {
        continue;
      }
      // Match process.env.KEY
      for (const m of content.matchAll(/\bprocess\.env\.([A-Z0-9_]+)/gi)) envKeys.add(m[1]);
      // Match process.env['KEY'] or process.env["KEY"]
      for (const m of content.matchAll(/\bprocess\.env\[['\"]([A-Z0-9_]+)['\"]\]/gi)) envKeys.add(m[1]);
      // Match import.meta.env.VAR (vite) and import.meta.env['VAR']
      for (const m of content.matchAll(/\bimport\.meta\.env\.([A-Z0-9_]+)/gi)) envKeys.add(m[1]);
      for (const m of content.matchAll(/\bimport\.meta\.env\[['\"]([A-Z0-9_]+)['\"]\]/gi)) envKeys.add(m[1]);
      // Match common string keys used with process.env or other env helpers
      for (const m of content.matchAll(/["'`]([A-Z0-9_]{3,})["'`]/g)) {
        const key = m[1];
        // Heuristic: include likely env-like uppercase keys with underscores
        if (/^[A-Z0-9_]+$/.test(key) && key.includes('_')) envKeys.add(key);
      }
    }
  }
}

walk(root);

// Add a small list of common keys used by this project as heuristics (won't duplicate)
const heuristic = [
  'DATABASE_URL','PORT','BASE_PATH','EXPO_PUBLIC_DOMAIN','EXPO_PUBLIC_REPL_ID','REPL_ID',
  'REPLIT_INTERNAL_APP_DOMAIN','REPLIT_DEV_DOMAIN','OPENAI_API_KEY','AI_INTEGRATIONS_OPENAI_BASE_URL',
  'PILOT_ACCESS_CODE','LOG_LEVEL','NODE_ENV'
];
for (const k of heuristic) envKeys.add(k);

const sorted = Array.from(envKeys).sort();
if (sorted.length === 0) {
  console.error('No environment variables found.');
  process.exit(1);
}

const lines = [];
lines.push('# .env.example — generated by scripts/extract-envs.js');
lines.push('# Fill in real secrets in your deployment platform (Render, etc.). Do NOT commit real secrets.');
lines.push('');
for (const k of sorted) {
  lines.push(`${k}=`);
}
const out = lines.join('\n') + '\n';

if (writeFlag) {
  const outPath = path.join(root, '.env.example');
  try {
    fs.writeFileSync(outPath, out, { encoding: 'utf8', flag: 'w' });
    console.log(`Wrote .env.example to ${outPath}`);
  } catch (e) {
    console.error('Failed to write .env.example:', e.message);
    process.exit(1);
  }
} else {
  process.stdout.write(out);
}
